### ISSUE TITLE
needs update to the latest version of flutter

### ISSUE THREAD

**Issue by Honelign** [gskinnerTeam/flutter_vignettes#20]
it says the project was made in the old version migrate now

**Comment by FranMaric** [comment]
Some vignettes can't be run on flutter 3. For this repo to stay useful it needs to be updated to work on new flutter sdk.

**Comment by esDotDev** [comment]
We don't currently have the resources to do this, but we're open to pull requests :)

**Comment by esDotDev** [comment]
closed with #25!
