### ISSUE TITLE
Unable to run dog_slider

### ISSUE THREAD

**Issue by sudo-kaizen** [gskinnerTeam/flutter_vignettes#6]
I am unable to run the dog_slider vignette on my computer. I get the error message shown below when I try

`
Compiler message: /C:/src/flutter/.pub-cache/hosted/pub.dev%2547/flare_flutter-1.7.3/lib/flare.dart:659:7: Error: The non-abstract class 'FlutterActor' is missing implementations for these members: - Actor.makeDropShadow - Actor.makeInnerShadow - Actor.makeLayerEffectRenderer Try to either - provide an implementation, - inherit an implementation from a superclass or mixin, - mark the class as abstract, or - provide a 'noSuchMethod' implementation. class FlutterActor extends Actor { ^^^^^^^^^^^^ /C:/src/flutter/.pub-cache/hosted/pub.dev%2547/flare_dart-2.3.0/lib/actor.dart:108:19: Context: 'Actor.makeDropShadow' is defined here. ActorDropShadow makeDropShadow(); ^^^^^^^^^^^^^^ /C:/src/flutter/.pub-cache/hosted/pub.dev%2547/flare_dart-2.3.0/lib/actor.dart:110:20: Context: 'Actor.makeInnerShadow' is defined here. ActorInnerShadow makeInnerShadow(); ^^^^^^^^^^^^^^^ /C:/src/flutter/.pub-cache/hosted/pub.dev%2547/flare_dart-2.3.0/lib/actor.dart:112:28: Context: 'Actor.makeLayerEffectRenderer' is defined here. ActorLayerEffectRenderer makeLayerEffectRenderer(); ^^^^^^^^^^^^^^^^^^^^^^^ Target kernel_snapshot failed: Exception: Errors during snapshot creation: null build failed. FAILURE: Build failed with an exception. * Where: Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780 * What went wrong: Execution failed for task ':app:compileFlutterBuildDebug'. > Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1 * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 10s Running Gradle task 'assembleDebug'... Running Gradle task 'assembleDebug'... Done                        10.8s Gradle task assembleDebug failed with exit code 1`

Steps to produce error

- Clone the project from Github
- cd into the dog_slider folder
- run `flutter pub get`
- After `Exit code 0`, run `flutter run` on the terminal

Flutter Environment

$ flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\src\flutter
    • Framework revision 27321ebbad (4 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\scata2\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\scata2\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\scata2\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

**Comment by andermoran** [comment]
Same error

**Comment by esDotDev** [comment]
Can't seem to reproduce this, it seems like some sort of issue with the Flare plugin you have installed. Can you try running   `flutter clean` and then `flutter upgrade`?

**Comment by esDotDev** [comment]
Closing for now. Please let us know if you still have this issue.
