### ISSUE TITLE
drink_rewards_list (warning): bottom overflowed by 0.651 pixels

### ISSUE THREAD

**Issue by sudo-kaizen** [gskinnerTeam/flutter_vignettes#7]
On running the drink_rewards_list vignette, I get the warning `bottom overflowed by 0.651 pixels` on the UI
![bottom overflowed by 0.651 pixels](https://user-images.githubusercontent.com/37955249/70853157-8c93ee00-1eaa-11ea-99cf-dfa8431d08d1.png)

Steps to reproduce

- Clone the project from Github
- Open the project folder from Android studio or VSCode
- Get packages using the IDE suggestions or from the terminal using `flutter pub get`
 Warning on the terminal
`I/flutter ( 6610): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 6610): The following assertion was thrown during layout:
I/flutter ( 6610): A RenderFlex overflowed by 0.651 pixels on the bottom.
I/flutter ( 6610):
I/flutter ( 6610): The relevant error-causing widget was:
I/flutter ( 6610):   Column file:///D:/D0m/Playground/flutter_vignettes/vignettes/drink_rewards_list/lib/demo.dart:92:18
I/flutter ( 6610):
I/flutter ( 6610): The overflowing RenderFlex has an orientation of Axis.vertical.
I/flutter ( 6610): The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
I/flutter ( 6610): black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
I/flutter ( 6610): Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
I/flutter ( 6610): RenderFlex to fit within the available space instead of being sized to their natural size.
I/flutter ( 6610): This is considered an error condition because it indicates that there is content that cannot be
I/flutter ( 6610): seen. If the content is legitimately bigger than the available space, consider clipping it with a
I/flutter ( 6610): ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
I/flutter ( 6610): like a ListView.
I/flutter ( 6610): The specific RenderFlex in question is: RenderFlex#f70e8 relayoutBoundary=up6 OVERFLOWING:
I/flutter ( 6610):   creator: Column ← Padding ← ConstrainedBox ← Container ← Align ← MediaQuery ← Padding ← SafeArea ←
I/flutter ( 6610):     Stack ← IconTheme ← IconTheme ← _InheritedCupertinoTheme ← ⋯
I/flutter ( 6610):   parentData: offset=Offset(13.7, 13.7) (can use size)
I/flutter ( 6610):   constraints: BoxConstraints(0.0<=w<=384.1, h=109.3)
I/flutter ( 6610):   size: Size(384.1, 109.3)
Syncing files to device Android SDK built for x86...
I/flutter ( 6610):   direction: vertical
I/flutter ( 6610):   mainAxisAlignment: spaceBetween
I/flutter ( 6610):   mainAxisSize: max
I/flutter ( 6610):   crossAxisAlignment: center
I/flutter ( 6610):   verticalDirection: down
I/flutter ( 6610): ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
I/flutter ( 6610): ════════════════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device Android SDK built for x86...             6,547ms (!)`

**Comment by esDotDev** [comment]
This should be fixed in the latest commit. Please confirm :)
